### ISSUE TITLE
If I type this.page I would like to see all the Playwright methods that are available

### ISSUE THREAD

**Issue by SabFloki** [testgitdl/cucumber-playwright-ang13#1]
f I type this.page I would like to see all the Playwright methods that are available

As we dont have inhouse feature provided by Playwright with cucumber, I would like to know if you are able to see all playwright methods while providing '.'

**Comment by testgitdl** [comment]
@SabFloki  please check out this link : https://github.com/testgitdl/playwright-cucumber-ang13
